variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
stages: 
     - build 
     - test
build:
     stage: build
     script:
        - cd Project_Backend/Chatbot
        - gradle assemble 
            
test: 
    stage: test
    script:
        - cd Project_Backend/Chatbot
        - gradle test
