package com.example.Chatbot.configuration;


import com.example.Chatbot.repository.NodeRepository;
import com.example.Chatbot.repository.impl.NodeEntity;
import lombok.AllArgsConstructor;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

@AllArgsConstructor
@Component
public class DatabaseDatainitializer {
    private NodeRepository nodeRepository;

    @EventListener(ApplicationReadyEvent.class)
    public void populateDatabaseInitialDummyData(){
        //This doesn't work anymore because of failing parentId please just use the scripts provided
        //Vraag and Antwoord needs to have at least some values so just do "" and be done with it
       if(nodeRepository.count() == 0)
       {
            nodeRepository.save(NodeEntity.builder().id(1l).nodeText("Account Credentials").answer("Please help us understand your problem better by choosing another option. ").vraag("Accountgegevens").antwoord("Help ons uw probleem beter te begrijpen door een keuze te maken van een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(2l).nodeText("Student Housing").answer("Please help us understand your problem better by choosing another option. ").vraag("Studentenwoningen").antwoord("Help ons uw probleem beter te begrijpen door een keuze te maken van een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(3l).nodeText("Office 365").answer("Please help us understand your problem better by choosing another option. ").vraag("Office 365").antwoord("Help ons uw probleem beter te begrijpen door een keuze te maken van een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(4l).nodeText("Forgot Password/Username").answer("You can reset your password/username here: https://goto.fontys.nl/wwvergeten/  or if you are an employee of Fontys or Declarant then you need to use https://intern.fontys.nl/wwselfservice/changepassword.aspx .").parentId(1L).vraag("Inloggegevens vergeten").antwoord("U kan uw wachtwoord hier opnieuw instellen: https://goto.fontys.nl/wwvergeten/ . Als medewerker of declarant moet u de volgende link nemen om uw wachtwoord te wijzigen https://intern.fontys.nl/wwselfservice/changepassword.aspx").build());
            nodeRepository.save(NodeEntity.builder().id(5l).nodeText("My account is hacked").answer("To help retrieve your account please contact the service desk: it-servicedesk@fontys.nl").parentId(1L).vraag("Mijn account is gehackt").antwoord("Om uw account terug te halen kunt u contact opnemen met de servicedesk: it-servicedesk@fontys.nl").build());
            nodeRepository.save(NodeEntity.builder().id(6l).nodeText("Other").answer("What are your having trouble with?").parentId(1L).vraag("Anders").antwoord("Waarmee heeft u problemen mee? kies een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(7l).nodeText("I am an international looking for housing").answer("Please fill in the form(https://goto.fontys.nl/forms/accommodation.form.location.eindhoven.and.tilburg.28245.en.htm) before the deadline: Fall semester 15 June, Spring semester 8 December. For more info visit: https://fontys.edu/Study-at-Fontys/Practical-information-1/Arriving-in-The-Netherlands-1/Accommodation.htm or send an email to internationalstudents@fontys.nl. ").parentId(2L).vraag("Ik ben een internationale student zoekend naar een woning").antwoord("U kunt naar de volgende website gaan voor meer concrete hulp (https://fontys.nl/Studeren/Studeren-in-Fontyssteden.htm) als u de stad waar u gaat studeren klikt en dan scroll naar de sectie 'op kamers' dan zal u een paar opties zien dat misschien kunnen helpen. Als u dit niet wil doen/niet oplost kunt u ook een mail sturen naar internationalstudents@fontys.nl.").build());
            nodeRepository.save(NodeEntity.builder().id(8l).nodeText("I want to stay at the social hub").answer("Fontys makes a pre-reservation of several rooms at the Social Hub in Eindhoven. You can book via this link Eindhoven - The Social Hub and fill in the group code. https://fontys.edu/Study-at-Fontys/Practical-information-1/Arriving-in-The-Netherlands-1/Accommodation/The-Social-Hub.htm").parentId(2L).vraag("Ik wil verblijven bij The social hub").antwoord("Fontys maakt een pre-reservatie voor meerdere kamers bij The Social Hub in Eindhoven. U kan boeken via de volgende link: https://fontys.edu/Study-at-Fontys/Practical-information-1/Arriving-in-The-Netherlands-1/Accommodation/The-Social-Hub.htm").build());
            nodeRepository.save(NodeEntity.builder().id(9l).nodeText("Other").answer("What are your having trouble with?").parentId(2L).vraag("Anders").antwoord("Waarmee heeft u problemen mee? kies een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(10l).nodeText("Can I get Office?").answer("On portal.office.com you can by clicking on 'Install Office', you may install it on 5 mobile devices, 5 tablets and 5 laptops or desktops. On Fontys computers Office is already installed so please don't click on 'install Office' on a Fontys computer").parentId(3L).vraag("kan ik Office krijgen?").antwoord("Àls u naar portal.office.com gaat kunt u kiezen voor de optie 'Apps instaleren' u mag Office installeren op 5 mobiele telefoons, 5 tablets en 5 laptops of desktops die privé zijn. Office is al geïnstalleerd op Fontys computers dus hoeft u niet op de optie 'Apps installeren' te klikken.").build());
            nodeRepository.save(NodeEntity.builder().id(11l).nodeText("Can I add an e-mail account?").answer("You can only add email accounts which support Exchange (no pop3 or imap).").parentId(3L).vraag("kan ik een e-mail account toevoegen?").antwoord("U kunt een email account toevoegen wat understeund Exchange (geen pop3 of imap).").build());
            nodeRepository.save(NodeEntity.builder().id(12l).nodeText("Other").answer("What are your having trouble with?").parentId(3L).vraag("Anders").antwoord("Waarmee heeft u problemen mee? kies een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(13l).nodeText("Welcome").answer("Hello! What can I help you with today?").vraag("Welkom").antwoord("Hallo! waarmee kan ik je vandaag mee helpen?").build());

            nodeRepository.save(NodeEntity.builder().id(14l).nodeText("Workplace").answer("Please help us understand your problem better by choosing another option.").parentId(22L).vraag("Werkplaats").antwoord("Help ons uw probleem beter te begrijpen door een keuze te maken van een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(15l).nodeText("Direct access problems").answer("I don't have a solution made for me yet please check: https://learn.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/troubleshooting-directaccess if it can solve your issue if not please contact via one of the following methods: Email: it-servicedesk@fontys.nl, Telephone: +31 8850 77777, Whatsapp: https://wa.me/31653721805 or one of the serivepoints https://connect.fontys.nl/diensten/IT/Paginas/(EN)-IT-Servicepoints.aspx ").parentId(14L).vraag("Direct access problemen").antwoord("Er is nog geen antwoord voor mij gemaakt probeer het optelossen door: https://learn.microsoft.com/nl-nl/troubleshoot/windows-server/networking/troubleshoot-directaccess-guidance  of neem contact op met iemand via een van de volgende methodes: Email: it-servicedesk@fontys.nl, Telephone: +31 8850 77777, Whatsapp: https://wa.me/31653721805 of een van de serivepoints: https://connect.fontys.nl/diensten/IT/Paginas/IT-Servicepoints.aspx").build());
            nodeRepository.save(NodeEntity.builder().id(16l).nodeText("Battery issues").answer("Please visit a IT team on your campus/building to check your computer").parentId(14L).vraag("Batterij problemen").antwoord("Bezoek een IT-team op uw campus/gebouw om uw computer te controleren.").build());
            nodeRepository.save(NodeEntity.builder().id(17l).nodeText("Sound issues").answer("I don't have a basic solution for you yet if you have windows you can try: https://support.microsoft.com/en-us/windows/fix-sound-or-audio-problems-in-windows-73025246-b61c-40fb-671a-2535c7cd56c8 . For Apple machines try: https://support.apple.com/en-us/HT203186 .Any other systems will probably also get help from the two previous links").parentId(14L).vraag("Geluid problemen").antwoord("Ik heb nog geen basis uitleg voor dit als u een Windows machine heeft kunt u de volgende website gebruiken (https://support.microsoft.com/nl-nl/windows/geluids-of-audioproblemen-in-windows-oplossen-73025246-b61c-40fb-671a-2535c7cd56c8) . Als u een apple apperaat heeft (https://support.apple.com/nl-nl/HT203186). Andere systemen zullen waarschijnlijk ook gehulpen worden met de vorige twee links ").build());
            nodeRepository.save(NodeEntity.builder().id(18l).nodeText("Camera issues").answer("I don't have a basic solution for you yet if you have a Windows machine you can try: https://support.microsoft.com/en-us/windows/camera-doesn-t-work-in-windows-32adb016-b29c-a928-0073-53d31da0dad5 .For Apple machines try: https://support.apple.com/en-us/HT211130 . Any other systems will probably also get help from the two previous links").parentId(14L).vraag("Camera problemen").antwoord("Ik heb nog geen basis uitleg voor dit als u een Windows machine heeft kunt u de volgende website gebruiken (https://support.microsoft.com/nl-nl/windows/camera-werkt-niet-in-windows-32adb016-b29c-a928-0073-53d31da0dad5). Als u een apple apperaat heeft https://support.apple.com/nl-nl/HT211130. Andere systemen zullen waarschijnlijk ook gehulpen worden met de vorige twee links ").build());

            nodeRepository.save(NodeEntity.builder().id(19l).nodeText("Wireless").answer("Please help us understand your problem better by choosing another option.").parentId(22L).vraag("Draadloos").antwoord("Help ons uw probleem beter te begrijpen door een keuze te maken van een volgende optie alstublieft").build());
            nodeRepository.save(NodeEntity.builder().id(20l).nodeText("How to connect to eduroam").answer("If you want to connect to eduroam you need to click on eduroam and then fill in your PCN@student.fontys.nl or  PCN@fontys.nl (PCN is your own personal number it's also the same as the one you use to login to outlook) and then your password. If this didn't help you can also try https://connect.fontys.nl/diensten/IT/manuals/Paginas/connectwitheduroam.aspx ").parentId(19L).vraag("Hoe te verbinden met edueroam").antwoord("U kunt met eduroam verbinden door op eduraom te klikken en dan invullen eerst met PCN@student.fontys.nl of PCN@fontys.nl (PCN is uw persoonlijke nummer het is ook dezelfde die u gebruikt om in te loggen met outlook ) en daarna uw wachtwoord. Als dit niet heeft geholpen of ander problemen zijn kunt u ook de volgende website proberen: https://connect.fontys.nl/diensten/IT/handleidingen/Paginas/verbindenmeteduroam.aspx ").build());

            nodeRepository.save(NodeEntity.builder().id(21l).nodeText("audio video").answer("If you have any problems with your Audiovisual Media you can go to https://connect.fontys.nl/diensten/IT/manuals/Paginas/Audiovisual-media.aspx to read one of the manuals to help fix it or you can contact a person via the following methods Telephone: +31 8850 77777. Email: it-servicedesk@fontys.nl. WhatsApp (text): +31 6 5372 1805. This is only possible from 8:00-17:00 on working days (Monday-Friday)").parentId(22L).vraag("Audiovisuele Middelen").antwoord("U kunt via (https://connect.fontys.nl/diensten/IT/handleidingen/Paginas/Audio_visuele_middelen.aspx) een van de handleiding kiezen of u kunt iemand contacteren via Telefoon: +31 8850 77777. Email: it-servicedesk@fontys.nl. Dit is alleen mogelijk tussen 8:00-17:00 op werkdagen (Maandag-Vrijdag)").build());

            //Less options at first selection
            nodeRepository.save(NodeEntity.builder().id(22l).nodeText("Other").answer("What are your having trouble with?").vraag("Anders").antwoord("Waarmee heeft u problemen mee? kies een volgende optie alstublieft").build());
        }
    }
}
